import py2neo
from py2neo import Graph, Node, Relationship, NodeMatcher, Relationship
import time

graph = Graph("http://localhost:7474/db/data/", user="neo4j", password="senha")

names = ["Política de botinas amarelas : o MDB-PMDB paulista de 1965 a 1988.",
"Significado nas artes visuais.",
"Clientelismo e política no Brasil do século XIX.",
"A construção do Terceiro Mundo : teorias do subdesenvolvimento na Romênia e no Brasil.",
"O PCB e a imprensa : os comunistas no imaginário dos jornais (1922-1989).",
"Concentração e desconcentração industrial em São Paulo, 1880-1990.",
"Combate ao racismo : discursos pronunciados e projetos apresentados.",
"A poética do silêncio : João Cabral de Melo Neto e Paul Celan.",
"Agosto : romance.",
"A testemunha silenciosa : duas novelas.",
"Ieipari : sacrifício e vida social entre os índios Arara (Caribe).",
"A literatura portuguêsa.",
"A literatura portuguêsa.",
"Primeiras estórias.",
"O cortiço.",
"Do formalismo estético trovadoresco.",
"O rito e o tempo : ensaios sobre o carnaval.",
"Marília de Dirceu de Tomás António Gonzaga : ou, a poesia como imitação e pintura.",
"Querida ilha.",
"Pau-de-Colher um pequeno Canudos : conotações políticas e ideológicas.",
"Maracatu de baque solto.",
"Urbanismo em fim de linha : e outros estudos sobre o colapso da modernização arquitetônica.",
"Cursos de estética.",
"Memórias da imigração : libaneses e sírios em São Paulo.",
"Os cangaceiros : romance de costumes sertanejos.",
"Romances brasileiros : uma leitura direcionada.",
"Os arquétipos literários.",
"A face e o verso : estudos sobre o homoerotismo II.",
"Luz neon : canção e cultura na cidade.",
"O estudo analítico do poema.",
"O primeiro século do Brasil : da expansão da Europa Ocidental aos governos gerais das terras do Br",
"A literatura latina.",
"História viajante : notações filosóficas.",
"Proverbios populares, maximas e observações usuaes colligidos na tradição oral.",
"O espaço do cidadão.",
"Espaço e método.",
"O pai de família e outros estudos.",
"Mulheres de papel : um estudo do imaginário em José de Alencar e Machado de Assis.",
"Molde nacional e fôrma cívica : higiene, moral e trabalho no projeto da Associação Brasileira de",
"A nervura do real : imanência e liberdade em Espinosa.",
"Espaço intra-urbano no Brasil.",
"Romeu e Julieta.",
"Pontos e bordados : escritos de história e política.",
"As ilusões da liberdade : a Escola Nina Rodrigues e a antropologia no Brasil.",
"A literatura brasileira : origens e unidade (1500-1960).",
"Uma teoria econômica da democracia.",
"Flores das Flores do mal de Baudelaire.",
"Mecenato pombalino e poesia neoclássica : Basílio da Gama e a poética do encômio.",
"Diário íntimo.",
"O teatro na estante : estudos sobre dramaturgia brasileira e estrangeira.",
"Notas sobre o culto aos orixás e voduns na Bahia de Todos os Santos, no Brasil, e na antiga Costa d",
"Modernizando a desigualdade : reestruturação da ideologia de gênero no Brasil, 1914-1940.",
"Brasília.",
"Lição do fogo : amor e erotismo em Octavio Paz.",
"Versificação portuguesa.",
"Variações sôbre o conto.",
"Cartas escolhidas.",
"Imposturas intelectuais.",
"Bang",
"Metamorfoses do espaço habitado : fundamentos teóricos e metodológicos da geografia.",
"O Museu da Inconfidência.",
"Quem tem medo da geopolítica?.",
"Odisséia.",
"A astúcia liberal : relações de mercado e projetos políticos no Rio de Janeiro (1820-1824).",
"História da Família no Brasil Colonial.",
"Carnavais, Malandros E Herois : Para Uma Sociologia Do Dilema Brasileiro.",
"Poesia e prosa completas.",
"Os parceiros do Rio Bonito : estudo sobre o caipira paulista e a transformação dos seus meios de v",
"Em demanda da poética popular : Ariano Suassuna e o Movimento Armorial.",
"Nova grammatica analytica da lingua portugueza.",
"A carne, a morte e o diabo na literatura romântica.",
"Histórias de cordéis e folhetos.",
"Poéticas do processo : arte conceitual no Museu.",
"O Brasil descobre a pesquisa científica : os museus e as ciências naturais no século XIX.",
"1932 : imagens construindo a História.",
"Entre a mão e os anéis : a Lei dos Sexagenários e os caminhos da abolição no Brasil.",
"Liberdade é uma calça velha, azul e desbotada : publicidade, cultura de consumo e comportamento po",
"A fabricação do imortal : memória, história e estratégias de consagração no Brasil.",
"A caminho do encontro : uma leitura de Contos novos.",
"Trajetórias geográficas.",
"A arte de descrever : a arte holandesa no século XVII.",
"A unidade da România ocidental.",
"Suma teológica.",
"Herbário etnobotânico (Banco de Dados) : as plantas do catimbó em Meleagro de Luis da Câmara Cas",
"A nação como artefato : deputados do Brasil nas cortes portuguesas (1821-1822).",
"Sete aulas sobre linguagem, memória e história.",
"A aventura do livro : do leitor ao navegador: conversações com Jean Lebrun.",
"Notas de advocacia gramatical : (estudinhos de linguagem portuguesa).",
"Coroas de glória, lágrimas de sangue : a rebelião dos escravos de Demerara em 1823 / c Emilia Vio",
"Cocanha : a história de um pais imaginário.",
"Antologia poética.",
"Formação econômica do Brasil.",
"A integração do negro à sociedade de classes.",
"Figurações Brasil anos 60 : neofigurações fantásticas e neo-surrealismo, novo realismo e nova o",
"A carreira e a lenda de Vasco da Gama.",
"Região e geografia.",
"Hercule Florence.",
"São Paulo : políticas públicas e habitação popular.",
"Nem tudo era italiano : São Paulo e pobreza, 1890-1915.",
"Tempos de escola : fontes para a presença feminina na educação: São Paulo - Século XIX.",
"I Seminário de Filologia e Língua Portuguesa, São Paulo, 19 e 20 de março de 1997.",
"A mísera sorte : a escravidão africana no Brasil holandês e as guerras do tráfico no Atlântico",
"A pedra mágica do discurso.",
"1930 : a crítica e o Modernismo.",
"O cacto e as ruínas : a poesia entre outras artes.",
"Anais do segundo Congresso Brasileiro de Crítica e História Literária.",
"A teia do fato : uma proposta de estudo sobre a memória histórica.",
"Teatro da fé : representação religiosa no Brasil e no México do século XVI.",
"América Latina no século XIX : tramas, telas e textos.",
"Por uma outra globalização : do pensamento único à consciência universal.",
"Um país, uma região : fim de século e modernidades na Argentina.",
"Olhares modernistas.",
"Marx : vida & obra.",
"A paixão segundo GH : romance.",
"Metamorfoses do mal : uma leitura de Clarice Lispector.",
"Crítica e tradução.",
"Cidade e natureza : proteção dos mananciais e exclusão social.",
"Brasil : mito fundador e sociedade autoritária.",
"Mulheres públicas.",
"Resumo de Ana.",
"Da monarquia à república : momentos decisivos.",
"Da senzala à colônia.",
"Cidade no Brasil em que termos?.",
"Jubiab",
"Seminário Carlos Drummond de Andrade--50 Anos de Alguma Poesia.",
"Guerra sem guerra : a mobilização e o cotidiano em São Paulo durante a Segunda Guerra Mundial.",
"O domínio espanhol no Brasil durante a monarquia dos Felipes 1580-1640.",
"Na senzala, uma flor : esperanças e recordações na formação da família escrava - Brasil Sudest",
"Esquerda e direita no eleitorado brasileiro : a identificação ideológica nas disputas presidencia",
"Guimarães Rosa : do feminino e suas estórias.",
"Roteiro para um narrador : uma leitura dos contos de Rubem Fonseca.",
"Memória da II Semana da História : 24 a 28 de novembro de 1980.",
"Graciliano Ramos e a fala das memórias.",
"A geração romântica.",
"História : análise do passado e projeto social.",
"Machado de Assis : o enigma do olhar.",
"A vida dos escravos no Rio de Janeiro (1808-1850).",
"A paz das senzalas : famílias escravas e tráfico atlântico, Rio de Janeiro, c. 1790-c. 1850.",
"Nacoes e nacionalismo desde 1780 : programa, mito e realidade.",
"A faca de dois gumes.",
"Cafundó, a África no Brasil : linguagem e sociedade.",
"Capitalismo e marginalidade na América Latina.",
"Tipologia documental de partidos e associações políticas brasileiras.",
"Acervo de pesquisas folclóricas de Mário de Andrade 1935-1938.",
"Espelho índio : a formação da alma brasileira.",
"A sociedade do espetáculo : comentários sobre a sociedade do espetáculo.",
"O cinema como agitador de almas : Argila, uma cena do Estado Novo.",
"A Eva barbada : ensaios de mitologia medieval.",
"Problemas da poética de Dostoiévski.",
"Bases da formação territorial do Brasil : o território colonial brasileiro no longo século XVI.",
"A sociabilidade do homem simples : cotidiano e história na modernidade anômala.",
"Dois irmãos.",
"O cinema brasileiro nos anos 90.",
"Meninos, poetas e heróis : aspectos de Cassiano Ricardo do modernismo ao Estado Novo.",
"O quinto século : André Rebouças e a construção do Brasil.",
"Sob o signo da nova ordem : intelectuais autoritários no Brasil e na Argentina (1914-1945).",
"Terra prometida : uma história da questão agrária no Brasil.",
"O império do Divino : festas religiosas e cultura popular no Rio de Janeiro, 1830-1900.",
"A colônia em movimento : fortuna e família no cotidiano colonial.",
"Dos filhos deste solo : mortos e desaparecidos políticos durante a ditadura militar - a responsabil",
"O Império do Brasil.",
"As festas no Brasil colonial.",
"A educação pela pedra e depois.",
"Variedades de história cultural.",
"As artes de enganar : um estudo das máscaras poéticas e biográficas de Gregorio de Mattos.",
"Um teatro fora do eixo : Porto Alegre, 1953-1963.",
"O Rio de Janeiro dos viajantes : o olhar britânico (1800-1850).",
"História de Santos.",
"O ruralismo brasileiro : 1888-1931.",
"As muitas faces da história : nove entrevistas.",
"As cidades na economia mundial.",
"A tradição regionalista no romance brasileiro, 1857-1945.",
"Cecília Meireles : o mundo contemplado.",
"Visão do paraíso : os motivos edênicos no descobrimento e colonização do Brasil.",
"No reino do desejado : a construção do sebastianismo em Portugal séculos XVI e XVII.",
"Os sete loucos & Os lança-chamas.",
"O abolicionismo.",
"Construçao da nação e escravidão no pensamento de José Bonifácio, 1783-1823.",
"Um palco sob as arcadas : o teatro dos estudantes de direito do Largo São Francisco, em São Paulo,",
"Macunaíma : o herói sem nenhum caráter.",
"O problema da consciência histórica.",
"Enigmas da modernidade-mundo.",
"Eu, o supremo.",
"Escritos.",
"À sombra da revolução mexicana : história mexicana contemporânea, 1910-1989.",
"Nos bares da vida : produção cultural e sociabilidade em São Paulo, 1940-1950.",
"Para onde vão os brasileiros? : imigrantes brasileiros no Japão.",
"Terra grávida.",
"Pais e filhos.",
"Realismo, racionalismo, surrealismo : a arte no entre-guerras.",
"Primitivismo, cubismo, abstração : começo do século XX.",
"Adeus, chamigo brasileiro : uma história da Guerra do Paraguai.",
"As trombetas de Jericó : teatros das vanguardas históricas.",
"A casa dos espíritos.",
"Poemas : Giorgos Seféris.",
"Casa-grande & senzala : formação da família brasileira sob o regime da economia patriarcal.",
"A vagabunda.",
"A queda do aventureiro : aventura, cordialidade e os novos tempos em Raízes do Brasil.",
"A globalização da pobreza : impactos das reformas do FMI e do Banco Mundial.",
"A via crucis do corpo.",
"A Legião Estrangeira.",
"Felicidade clandestina : contos.",
"O texto poético como documento social.",
"Água viva : ficção.",
"Esboço histórico sobre a província do Cear",
"Contos : uma antologia.",
"Contribuição Bantu na música popular brasileira : perspectivas etnomusicológicas.",
"Guimarães Rosa : do ícone ao símbolo : ensaio de estilística.",
"A América de Rugendas : obras e documentos.",
"Metamorfoses do espaço habitado : fundamentos teóricos e metodológicos da Geografia.",
"Reforma social ou revolução ?.",
"Crescimento demográfico e evolução agrária paulista : 1700-1836.",
"Obra crítica.",
"Obras.",
"Reforma agrária : o impossível diálogo.",
"O Brasil : território e sociedade no início do século XXI.",
"O antropólogo e sua magia : trabalho de campo e texto etnográfico nas pesquisas antropológicas so",
"Cor, profissão e mobilidade : o negro e o rádio de São Paulo.",
"Números anônimos, 1990-1993.",
"A leitora Clarice Lispector.",
"Cintilações de uma alma brasileira.",
"Cartografia e diplomacia no Brasil do século XVIII.",
"Idéias teatrais : o século XIX no Brasil.",
"Memória do fogo.",
"Mutações do cativeiro : escritos de psicologia e política.",
"Cidade de muros : crime, segregação e cidadania em São Paulo.",
"Nove, novena : narrativas.",
"Um espaço para a ciência : a formação da comunidade científica no Brasil.",
"O mundo das calçadas : por uma política democrática de espaços públicos.",
"Descartes : uma biografia intelectual.",
"Mundo húngaro no Brasil : do século passado até 1942.",
"A solidão povoada.",
"O mal que se adivinha : polícia e menoridade no Rio de Janeiro, 1910-1920..",
"O centro da metrópole Paulistana : expansão recente.",
"Os parceiros do Rio Bonito : estudo sobre o caipira paulista e a transformação dos seus meios de v",
"Rio Branco : o Brasil no mundo.",
"Destinos mistos : os críticos do grupo clima em São Paulo (1940-68).",
"A política nuclear no Brasil.",
"Contos escolhidos.",
"Elementos de filologia românica.",
"A conspiração mundial dos judeus, mito ou realidade? : análise dos Protocolos e outros documentos",
"Homens livres na ordem escravocrata.",
"Insultos impressos : a guerra dos jornalistas na Independência, 1821-1823.",
"Inimigos fiéis : história, guerra e xamanismo na Amazônia.",
"O trato dos viventes : formação do Brasil no Atlântico Sul, séculos XVI e XVII.",
"A história à prova do tempo : da história em migalhas ao resgate do sentido.",
"Guimarães Rosa : magma e gênese da obra.",
"Dialética da colonização.",
"História concisa do Brasil.",
"O artista da corte : os antecedentes dos artistas modernos.",
"Máquina de gêneros : novamente descoberta e aplicada a Castiglione, Della Casa, Nóbrega, Camões,",
"Morte e alteridade em Estas estórias.",
"O indivíduo e a sociedade na Guiana : um estudo comparativo sobre a organização social ameríndia",
"Por uma nova história urbana.",
"Eros : dialética e retórica.",
"Templos de civilização : a implantação da escola primária graduada no estado de São Paulo (189",
"O índio brasileiro e a Revolução Francesa : as origens brasileiras da teoria da bondade natural.",
"Honra e pátria.",
"O Exército na consolidação do Império : um estudo histórico sobre a política militar conservad",
"A Revista do Brasil : um diagnóstico para a (n)ação.",
"Inútil poesia e outros ensaios breves.",
"Introdução ao estudo da história geral.",
"O léxico de Guimarães Rosa.",
"Diálogos brasileiros : uma análise da obra de Roger Bastide.",
"O longo amanhecer : reflexões sobre a formação do Brasil.",
"História da historiografia : capítulos para uma história das histórias da historiografia.",
"O dialeto caipira : gramática, vocabulário.",
"Bom-Crioulo.",
"Lucas Procópio.",
"Capitalismo histórico e civilização capitalista.",
"Lucíola : um perfil de mulher.",
"A pata da gazela.",
"Dom Casmurro.",
"Navegantes, bandeirantes, diplomatas : um ensaio sobre a formação das fronteiras do Brasil.",
"Ontologia do ser social : a falsa e a verdadeira ontologia de Hegel.",
"Roteiro de Macunaíma.",
"Correspondência de Cabral com Bandeira e Drummond.",
"O método Brecht.",
"Breve história da Hospedaria de Imigrantes e da imigração para São Paulo.",
"Formação da diplomacia econômica no Brasil : as relações econômicas internacionais no Império",
"Eu e voc",
"Estructura y función de los tiempos en el lenguaje.",
"O porto vermelho : a maré revolucionária (1930-1951).",
"Homens de grossa aventura : acumulaçao e hierarquia na praça mercantil do Rio de Janeiro (1790-183",
"Cerimônias de posse na conquista européia do Novo Mundo (1492-1640).",
"Introdução ao desenvolvimento : enfoque histórico-estrutural.",
"Cecília Meirelles : mito e poesia.",
"Outros achados e perdidos.",
"As concepções lingüísticas no século XVIII : a gramática portuguesa.",
"Poética e poesia no Brasil (Colônia).",
"Indústria cultural, informação e capitalismo.",
"Esculpindo a cultura na forma Brasil : o departamento de cultura de São Paulo (1935-1938).",
"Cecília em Portugal : ensaio biográfico sobre a presença de Cecília Meireles na terra de Camões",
"Leituras brasileiras : itinerários no pensamento social e na literatura.",
"Obra crítica 1.",
"Inventário DEOPS : módulo II--estudantes : os subversivos das arcadas.",
"João Cabral e o poema dramático : Auto do Frade (poema para vozes).",
"Ônibus : uma história do transporte coletivo e do desenvolvimento urbano no Brasil.",
"Marco Zero.",
"Historia social do jazz.",
"A fala dos quartéis e as outras vozes.",
"Chocolate, piratas e outros malandros : ensaios tropicais.",
"O diabo : a máscara sem rosto.",
"O negócio do Brasil : Portugal, os Países Baixos e o Nordeste 1641-1669.",
"Seqüências brasileiras : ensaios.",
"Através da rótula : sociedade e arquitetura no Brasil, séculos XVII a XX.",
"A Aventura brasileira de Blaise Cendrars : ensaio, cronologia, filme, depoimentos, antologia, desenh",
"História da literatura de Mato Grosso : século XX.",
"Machado de Assis, escritor em formação : a roda dos jornais.",
"O mito do eterno retorno : arquétipos e repetição.",
"A donzela-guerreira : um estudo de gênero.",
"Uma história da leitura.",
"Grammatica descripitiva baseada nas doutrinas modernas.",
"História das inquisições : Portugal, Espanha e Itália - séculos XV-XIX.",
"Fluxo-floema.",
"Monstros e monstrengos do Brasil : ensaio sobre a zoologia fantástica brasileira nos séculos XVII",
"Gramática de usos do português.",
"O desaparecimento do dote : mulheres, famílias e mudança social em São Paulo, Brasil, 1600-1900.",
"Maldita guerra : nova história da Guerra do Paraguai.",
"Mito e discurso político : uma análise a partir da campanha eleitoral de 1994.",
"Textos para o movimento negro.",
"Itinerário político do romance pós-64 : a festa.",
"Um lugar do tamanho do mundo : tempos e espaços da ficção em João Guimarães Rosa.",
"Manual do agricultor brasileiro.",
"Ladrilhadores e semeadores : a modernização brasileira no pensamento político de Oliveira Vianna,",
"Lembranças do Brasil : teoria política, história e ficção em Grande Sertão: veredas.",
"A república mundial das letras.",
"Da fera à Loira : sobre contos de fadas e seus narradores.",
"A urbanização brasileira.",
"A Berlim de Bertold Brecht : um álbum dos anos 20.",
"Historiografia luso-brasileira contemporânea.",
"Como e por que ler a poesia brasileira do século XX.",
"Memória em branco e negro : olhares sobre São Paulo.",
"Um funcionário da monarquia : ensaio sobre o segundo escalão.",
"Balzac e a costureirinha chinesa : romance.",
"As identidades do Brasil : de Varnhagen a FHC.",
"Pancho Villa.",
"Ecos da folia : uma história social do carnaval carioca entre 1880 e 1920.",
"Metrópole e cultura : São Paulo no meio do século XX.",
"Cultura popular : temas e questões.",
"Classes, raças e democracia.",
"Presença da literatura brasileira.",
"A passagem de Sartre e Simone de Beauvoir pelo Brasil em 1960.",
"Jackson do Pandeiro : o rei do ritmo.",
"Dias em Trujillo : um antropólogo brasileiro em Honduras.",
"Dorival Caymmi : o mar e o tempo.",
"Villa Kyrial : crônica da Belle Époque paulistana.",
"Viver e sobreviver em uma vila colonial : Sorocaba, séculos XVIII e XIX.",
"Impressões de um amador : textos esparsos de crítica, 1882-1909.",
"Cantoria nordestina : música e palavra.",
"Charles Frederick Hartt, um naturalista no império de Pedro II.",
"Os olhos do império : relatos de viagem e transculturação.",
"Destino ímpar : sobre a formação de Florestan Fernandes.",
"Mitos, emblemas, sinais : morfologia e história.",
"Olhos de madeira : nove reflexões sobre a distância.",
"Situação-limite e memória : a reconstrução do mundo dos familiares de desaparecidos da Argentin",
"Estética.",
"Os contos de Belazarte.",
"A cidade em Portugal : uma geografia urbana.",
"O monge negro.",
"Coração partido : uma análise da poesia reflexiva de Drummond.",
"O arcaísmo como projeto : mercado atlântico, sociedade agrária e elite mercantil em uma economia",
"Tradição e modernidade : Afonso Schmidt e a literatura paulista, 1906-1928.",
"Lutas de famílias no Brasil : introdução ao seu estudo.",
"Uma casa luso-afro-portuguesa com certeza : emigrações e metamorfoses da Umbanda em Portugal.",
"O preço da leitura : leis e números por detrás das letras.",
"Igreja e camponeses : teologia da libertação e movimentos sociais no campo : Brasil e Peru, 1964-1",
"Raízes do riso : a representação humorística na história brasileira da Belle Époque aos primei",
"Di Cavalcanti ilustrador : trajetória de um jovem artista gráfico na imprensa (1914-1922).",
"Textos de intervenção.",
"Ensaios enveredados.",
"Drummond : da Rosa do povo à rosa das trevas.",
"Edusp, um projeto editorial.",
"Homens de negócio : a interiorização da metrópole e do comércio nas Minas setecentistas.",
"Liberdade antes do liberalismo.",
"A guerra dos bárbaros : povos indígenas e a colonização do sertão nordeste do Brasil, 1650-1720",
"Poesia e pintura ou pintura e poesia : tratado seiscentista de Manuel Pires de Almeida.",
"50 anos do CNPQ : contados pelos seus presidentes.",
"Literatura e resistência.",
"Ideologias geográficas : espaço, cultura e política no Brasil.",
"A gênese da geografia moderna.",
"Território e história no Brasil.",
"Comércio e vida urbana na cidade de São Paulo (1889-1930).",
"História da história do Brasil.",
"Estado e Nação no fim dos Impérios Ibéricos no Prata : 1808-1828.",
"Águas revoltas : história das enchentes em Santo Andr",
"O sistema dos objetos.",
"José de Alencar : o poeta armado do século XIX.",
"Idéias em movimento : a geração 1870 na crise do Brasil-Império.",
"Através do Brasil : narrativa.",
"Pagu, Patrícia Galvão : livre na imaginação, no espaço e no tempo.",
"As noites do ginásio : teatro e tensões culturais na Corte (1832-1868).",
"Oliver Twist.",
"João do Rio : a cidade e o poeta : o olhar de flâneur na belle époque tropical.",
"Metafísica.",
"Revistas em revista : imprensa e práticas culturais em tempos de República, São Paulo (1890-1922)",
"Frei Joaquim do Amor Divino Caneca.",
"Soberania : a construção de um conceito.",
"Caos e governabilidade no moderno sistema mundial.",
"Sinta o drama.",
"Antologia ilustrada dos cantadores.",
"A revolução russa de 1917.",
"Cacilda Becker : fúria santa.",
"Cinema, trajetória no subdesenvolvimento.",
"Homo sacer : o poder soberano e a vida nua I.",
"História e interpretação de Os Sertões.",
"O legado de Eszter.",
"O Otelo brasileiro de Machado de Assis : um estudo de Dom Casmurro.",
"O rei no espelho : a monarquia portuguesa e a colonização da América (1640-1720).",
"O perigo amarelo em tempos de guerra, 1939-1945.",
"A cultura do crime e da lei, 1889-1930.",
"O engenhoso fidalgo D. Quixote de La Mancha : primeiro livro.",
"O homem e sua hora e outros poemas.",
"Escritos urbanos.",
"Tarsila : sua obra e seu tempo.",
"Jardins da provocação : poemas 1976/1980.",
"Ilíada de Homero.",
"Atas do Seminário Internacional Brasil/Itália : vanguardas.",
"Ponto de vida : cidadania de mulheres faveladas.",
"A evolução territorial do municipio de Sorocaba.",
"Rio Paranapanema : da nascente à foz = Paranapanema river : from source to mouth.",
"Presente e futuro.",
"Índios e africanos na Jundiaí colonial.",
"A máquina.",
"Céu, inferno : ensaios de crítica literária e ideológica.",
"MST, movimento dos trabalhadores rurais sem-terra : formação e territorialização em São Paulo.",
"As idéias lingüísticas de Mário de Andrade.",
"Grande sertão : veredas.",
"Os miseráveis.",
"A conquista do oeste : a fronteira na obra de Sérgio Buarque de Holanda.",
"Zacarias de Góis e Vasconcellos.",
"Crítica e crise : uma contribuição à patogênese do mundo burguês.",
"O império marítimo português 1415-1825.",
"As imagens de um teatro popular.",
"Teatro completo : Qorpo-Santo.",
"Mímesis : desafio ao pensamento.",
"Os rumos da cidade : urbanismo e modernização em São Paulo.",
"Orfeu e o poder : o Movimento Negro no Rio de Janeiro e São Paulo (1945-1988).",
"Arte para quê? : a preocupação social na arte brasileira, 1930-1970 : subsídio para uma históri",
"Adoniran Barbosa : o poeta da cidade : trajetória e obra do radioator e cancionista, os anos 50.",
"Entre passos e rastros : presença judaica na literatura brasileira contemporânea.",
"Vidas de entremeio : assimilação e marginalização na Áustria, no Brasil e na África Ocidental,",
"A nau de Icaro : e, Imagem e miragem da lusofonia.",
"Mitologia da saudade, seguido de Portugal como destino.",
"Poesia, mito e história no modernismo brasileiro.",
"Um mestre na periferia do capitalismo : Machado de Assis.",
"A década do impasse : da Rio-92 à Rio+10.",
"Por uma geografia nova : da crítica da geografia a uma geografia crítica.",
"Escravos, roceiros e rebeldes.",
"A resistência anarquista : uma questão de identidade (1927-1937).",
"Emblemas da sagração armorial : Ariano Suassuna e o Movimento Armorial (1970-1976).",
"Lampião, o sertão e sua gente.",
"As mil faces de um herói-canalha e outros ensaios.",
"Uma São Paulo alemã : vida quotidiana dos imigrantes germânicos na região da capital (1827-1889)",
"São Paulo antigo : 1554 a 1910.",
"Ronda da meia-noite.",
"São Paulo de meus amores.",
"A democracia intolerante : Dutra, Adhemar e a repressão do Partido Comunista (1946-1950).",
"A epopéia bandeirante : letrados, instituições, invenção histórica, 1870-1940.",
"Arquivo em imagens.",
"O mundo de Homero.",
"Primeiras trovas burlescas & outros poemas.",
"Dez liçoes : sobre estudos culturais.",
"A ditadura escancarada.",
"A revolução brasileira.",
"Negro nas terras do ouro : cotidiano e solidariedade século XVIII.",
"Nacional estrangeiro : história social e cultural do modernismo artístico em São Paulo.",
"Morravagin : romance O fim do mundo filmado pelo Anjo Notre-Dame.",
"De Anchieta aos concretos : poesia brasileira no jornal.",
"A era Vargas.",
"Leituras 2 : a regiao dos filosofos.",
"A grande ilusão.",
"O nascimento político do Brasil : as origens do estado e da nação (1808-1825).",
"Palavra, imagem e poder : o surgimento da imprensa no Brasil do século XIX.",
"Senhores da memória : uma história do Nambiquara do cerrado.",
"A modernidade e os modernos.",
"A educacao na revisao constitucional de 1925-1926.",
"Semana de 22 : entre vaias e aplausos.",
"Dez lições sobre o romance inglês do século XVIII.",
"Ronda da meia-noite : vicios, misérias e esplendores da cidade de São Paulo.",
"Imaginário e viajantes no Brasil do século XIX : cultura e cotidiano, tradição e resistência.",
"Poesia completa : Cecília Meireles .",
"Carlos & Mário : correspondência completa entre Carlos Drummond de Andrade (inédita) e Mário de",
"A queda do escravismo colonial : 1776-1848.",
"Machado de Assis : o enigma do olhar.",
"A América Latina na época colonial.",
"O discurso filosófico da modernidade : doze lições.",
"Os carrascos voluntários de Hitler : o povo alemão e o Holocausto.",
"Nas malhas da letra : ensaios.",
"Villa Kyrial : crônica da Belle Époque paulistana.",
"Estudos de história da cultura clássica.",
"Commentariolus : pequeno comentário de Nicolau Copérnico sobre suas próprias hipóteses acerca do",
"O pais distorcido : o Brasil, a globalização e a cidadania.",
"As cidades brasileiras e o patrimônio cultural da humanidade.",
"Cinema : arte & indústria.",
"Retrato interrompido da vida de Euclides da Cunha.",
"A inexistência da terra firme : a imigração galega em São Paulo 1946-1964.",
"Graciliano Ramos : cidadão e artista.",
"Leituras 3 : nas fronteiras da filosofia.",
"Atlas do romance europeu : 1800-1900.",
"Legenda áurea : vida de santos.",
"Gabriela Mistral & Cecilia Meireles.",
"Imigrantes judeus do Oriente Médio : São Paulo e Rio de Janeiro.",
"Novo mundo : as cartas que batizaram a América.",
"Poesias completas.",
"A loucura de Isabella e outras comédias da Commedia Dell'Arte.",
"João Guimarães Rosa e a saudade.",
"Economia espacial : críticas e alternativas.",
"Cem anos de solidão.",
"José Antônio Pimenta Bueno, Marquês de São Vicente.",
"José Bonifácio de Andrada e Silva.",
"Literatura oral para a infância e a juventude : lendas, contos & fábulas populares no Brasil.",
"Literatura e cordialidade : o público e o privado na cultura brasileira.",
"Deslocamentos : experiências de arte-educação na periferia de São Paulo.",
"O folclore em questão.",
"Os domínios de natureza no Brasil : potencialidades paisagísticas.",
"O velho mundo desce aos infernos : auto-análise da modernidade após o trauma de junho de 1848 em P",
"Paraísos artificiais : o romantismo de José de Alencar e sua recepção crítica.",
"Terra, trabalho e poder : o mundo dos engenhos no Nordeste colonial.",
"Em busca do inespecífico : leitura de amar, verbo intransitivo de Mário de Andrade.",
"Retrato de Portinari.",
"Poesías completas.",
"O desencantamento do mundo : todos os passos do conceito em Max Weber.",
"Ficção científica, fantasia e horror no Brasil, 1875 a 1950.",
"Autobibliografias : solicitação do livro na ficção de Machado de Assis.",
"Cartas do Brasil : 1626-1697 Estado do Brasil e Estado do Maranhão e Grã Par",
"Xingu : o velho Káia (conta a história do seu povo).",
"O rei da vela.",
"Escritos sobre poesia & alguma ficção.",
"Belenzinho, 1910 : retrato de uma época.",
"Viagem ao Brasil, II : a expedição philosophica pelas capitanias do Pará, Rio Negro, Mato Grosso",
"Pioneiros e empreendedores : a saga do desenvolvimento no Brasil.",
"Depois da paixão política.",
"Brazil @digitaldivide.com : confronting inequality in the information society.",
"EMBRAER : elos entre estado e mercado.",
"Literatura como missão : tensões sociais e criação cultural na Primeira República.",
"Benedito Calixto e a construção do imaginário republicano.",
"Política externa da primeira república : os anos de apogeu (de 1902 a 1918).",
"Teatro em aberto.",
"Diplomacia em alto-mar : depoimento ao CPDOC.",
"Oliveira Vianna : de Saquarema à Alameda São Boaventura, 41--Niterói o autor, os livros, a obra.",
"Noite e musica na poesia de Carlos Drummond de Andrade.",
"Correspondência com seu tradutor alemão Curt Meyer-Clason (1958-1967).",
"Sobrados e mucambos : decadência do patriarcado rural e desenvolvimento do urbano.",
"Na trilha do Jeca : Monteiro Lobato e a formação do campo literário no Brasil.",
"A ditadura derrotada.",
"Bim bom : a contradição sem conflitos de João Gilberto.",
"A fronda dos mazombos : nobres contra mascates, Pernambuco, 1666-1715.",
"O controle ideológico na USP (1964-1978).",
"Um imenso Portugal : história e historiografia.",
"Ariel.",
"Portugal e Brasil na crise do antigo sistema colonial (1777-1808).",
"Poesia completa : conforme as disposições do autor.",
"As crônicas do Rio Amazonas : tradução, introdução e notas etno-históricas sobre as antigas po",
"A Casa de Dona Yay",
"Sentimento do Brasil : Caio Prado Júnior, continuidades e mudanças no desenvolvimento da sociedade",
"Perversão da retórica, retórica da perversão : moralidade e forma literária em As ligações p",
"A milésima segunda noite da avenida Paulista e outras reportagens.",
"Globalização e agricultura : a região de Ribeirão Preto - SP.",
"Antropologia da razão : ensaios de Paul Rabinow.",
"Vozes em branco e preto : a representação literária da fala não-padrão.",
"Os signos da opressão : história e violência nas prisões brasileiras.",
"Correspondência com seu tradutor italiano Edoardo Bizzarri.",
"Cartas a um jovem escritor e suas respostas.",
"A idéia modernista.",
"Rebelião escrava no Brasil : a história do levante dos Malês em 1835.",
"Contra-revolução e revolta.",
"O jovem rei encantado : expectativas do messianismo régio em Portugal, séculos XIII A XVI.",
"O século XIX e a história : o caso Fustel de Coulanges.",
"Luta subterrânea : o PCB em 1937-1938.",
"Cidades imaginárias : o Brasil é menos urbano do que se calcula.",
"A pedagogia do espectador.",
"A natureza do espaço : técnica e tempo, razão e emoção.",
"Como fazer análise diplomática e análise tipológica de documento de arquivo.",
"Capitu e a mulher fatal : análise da presença francesa em Dom Casmurro.",
"Sociologia e antropologia.",
"O tempo Saquarema : a formação do estado imperial.",
"Estes penhascos : Cláudio Manuel da Costa e a paisagem das Minas Gerais 1753-1773.",
"Águas encantadas de Chacororé : natureza, cultura, paisagens e mitos do Pantanal.",
"Economia colonial no Brasil nos séculos XVI e XVII : elementos de história econômica aplicados",
"Teatro da ruptura : Oswald de Andrade.",
"A ocupação do pontal do Paranapanema.",
"Feitores do corpo, missionários da mente : senhores, letrados e o controle dos escravos nas améric",
"Religião como tradução : missionários, Tupi e Tapuia no Brasil colonial.",
"Machado de Assis, historiador.",
"O tupi e o alaúde : uma interpretação de Macunaíma.",
"Formas breves.",
"Na Boca do Sertão : o perigo político no interior do Estado de São Paulo (1930-1945).",
"O Marquês de Pombal e a sua época.",
"O olhar e a cena : melodrama, Hollywood, Cinema Novo, Nelson Rodrigues.",
"Esquecidos por Deus : monstros no mundo europeu e ibero-americano, séculos XVI-XVIII.",
"Coleções e expedições vigiadas : os etnólogos no Conselho de Fiscalização das Expedições Ar",
"Escravidão e história econômica : demografia de Minas Gerais, 1720-1888.",
"O povoamento da Bahia : suas causas economicas.",
"A ficção da escrita.",
"Libertinagem : Estrela da manhã : edição crítica.",
"Trouxa frouxa.",
"Relatório Cruls : Relatório da Comissão Exploradora do Planalto Central do Brasil.",
"Esperando Foucault, ainda.",
"A África e os africanos na formação do mundo Atlântico 1400-1800.",
"Os leitores de Machado de Assis : o romance machadiano e o público de literatura no século 19.",
"América Latina no século XIX : tramas, telas e textos.",
"Fé e milagre : ex-votos pintados em madeira: séculos XVIII e XIX.",
"Tópica no lirismo galaico-português.",
"Correspondências.",
"Negócios jesuíticos : o cotidiano da administração dos bens divinos.",
"A pintura da vida moderna : Paris na arte de Manet e seus seguidores.",
"A vida literária no Brasil durante o romantismo.",
"O Rio de Janeiro imperial.",
"Iemanjá & Oxum : iniciações, Ialorixás e Olorixás.",
"A dominação masculina.",
"Pagu: literatura e revolução : um estudo sobre o romance Parque industrial.",
"As palavras e a Lei : direito, ordem e justiça na história do pensamento jurídico moderno.",
"Livro e liberdade.",
"Mãe judia, 1964.",
"Nascimento da antropologia cultural : a obra de Franz Boas.",
"Rui Barbosa : pondo as idéias no lugar.",
"O espaço dividido : os dois circuitos da economia urbana dos paises subdesenvolvidos.",
"A metodologia de Max Weber : unificação das ciências culturais e sociais.",
"Fatos do espírito humano.",
"São Paulo naquele tempo (1895-1915).",
"Teorias da arte moderna.",
"O romantismo e a idéia de nação no Brasil (1830-1870).",
"A identidade internacional do Brasil e a política externa brasileira : passado, presente e futuro.",
"As camélias do Leblon e a abolição da escravatura : uma investigação de história cultural.",
"Ao correr da pena.",
"Paulística etc..",
"Do espiritual na arte : e na pintura em particular.",
"Enciclopédia caiçara : falares caiçaras.",
"O cancioneiro de Lésbia.",
"A ditadura encurralada.",
"De Vasco a Cabral : oriente e ocidente nas navegações oceânicas.",
"Um rio chamado tempo, uma casa chamada terra : romance.",
"O rei ausente : festa e cultura política nas visitas dos Filipes a Portugal (1581 e 1619).",
"Domingos Caldas Barbosa : o poeta da viola, da modinha e do lundu (1740-1800).",
"Ponta de lança.",
"Revolução do cinema novo.",
"Kant e o fim da metafísica.",
"Antônio Vieira, profecia e polêmica.",
"O selvagem e o novo mundo : ameríndios, humanismo e escatologia.",
"Anarquismo e sindicalismo revolucionário : trabalhadores e militantes em São Paulo na Primeira Rep",
"Trovar claro : poemas.",
"Vários escritos.",
"Páginas de sensação : literatura popular e pornográfica no Rio de Janeiro ( 1870-1924).",
"O cru e o cozido.",
"Elizabeth Costello : oito palestras.",
"Academias de arte : passado e presente.",
"As Bienais de São Paulo : da era do Museu à era dos curadores (1951-2001).",
"O castelo de Axel : estudo sobre a literatura imaginativa de 1870 a 1930.",
"Influências e impasses : Drummond e alguns contemporâneos.",
"Ingleses no Brasil : aspectos da influência britânica sobre a vida, a paisagem e a cultura do Bras",
"Pisando fora da própria sombra : a escravidão por dívida no Brasil contemporâneo.",
"Planejamento e zoneamento : São Paulo 1947-1972.",
"Tesouro descoberto no máximo rio Amazonas.",
"O cosmopolitismo do pobre : crítica literária e crítica cultural.",
"Terra paulista : história, arte e costumes.",
"Estruturas : ensaio sobre o romance de Graciliano.",
"Noturno do Chile.",
"O erro de Hamlet : poesia e dialética em Murilo Mendes.",
"Para uma nova história.",
"A interiorização da metrópole e outros estudos.",
"Castello : a marcha para a ditadura.",
"Às portas da revolução : escritos de Lenin de 1917.",
"Além do golpe : versões e controvérsias sobre 1964 e a ditadura militar.",
"O livro de ouro do carnaval brasileiro.",
"Testemunha ocular : história e imagem.",
"Segredos guardados : orixás na alma brasileira.",
"Esquecidos e renascidos : historiografia acadêmica luso-americana, 1724-1759.",
"Escritura e nomadismo : entrevistas e ensaios.",
"Guerreiros e jesuítas na utopia do Prata.",
"Noções de analise histórico-literária.",
"Pensando o espaço do homem.",
"A minha patria.",
"Grandesertão.br : o romance de formação do Brasil.",
"O primo Basílio : Texto integral.",
"Poesia e prosa reunidas de Sousândrade.",
"Iniciação à literatura brasileira : (resumo para principiantes).",
"A dimensão da noite e outros ensaios.",
"O sertão itinerante : expedições da capitania de São Paulo no século XVIII.",
"Desclassificados do ouro : a pobreza mineira no século XVIII.",
"Da totalidade ao lugar.",
"Artes plásticas na Semana de 22.",
"Douradense : a agonia de uma ferrovia.",
"Trincheira, palco e letras : crítica, literatura e utopia no Brasil.",
"Itinerário de uma viagem à Alemanha.",
"A dinâmica da cultura : ensaios de antropologia.",
"A Revolução Farroupilha.",
"O bruxo do Cosme Velho : Machado de Assis no espelho.",
"Vidas de romance : as mulheres e o exércicio de ler e escrever no entresséculos 1890-1930.",
"As raízes clássicas da historiografia moderna.",
"Os estudantes, os intelectuais e a luta de classes.",
"Ensaios para uma sócio-história do português brasileiro.",
"Artes de civilizar : medicina, higiene e educação escolar na Corte Imperial.",
"Bellini e os espíritos.",
"Bahia indígena : encontro de dois mundos : verdade do descobrimento do Brasil.",
"A propósito de águas virtuosas : formação e ocorrências de uma estação balneária no Brasil.",
"O jogo do belo e do feio.",
"A formação da antropologia americana 1883-1911 : antologia.",
"Três canções de Tom Jobim.",
"Os métodos da História : introdução aos problemas, métodos e técnicas da história demográfic",
"Carlota Joaquina na corte do Brasil.",
"Rachel Whiteread.",
"As seduções da ordem : violência, criminalidade e administração da justiça : Minas Gerais -- s",
"Notas de literatura I.",
"Obras reunidas.",
"Ser nobre na colônia.",
"Idea : contribuição à história do conceito da antiga teoria da arte.",
"A outra Independência : o federalismo pernambucano de 1817 a 1824.",
"Angola e Moçambique : experiência colonial e territórios literários.",
"A hidra e os pântanos : mocambos, quilombos e comunidades de fugitivos no Brasil (séculos XVII-XIX",
"A ideologia da sociedade industrial.",
"A história.",
"O albatroz e o chinês.",
"Cultura e sociedade no Brasil : ensaios sobre idéias e formas.",
"Os descaminhos do São Francisco.",
"Lembranças de São Paulo : o interior paulista nos cartões-postais e álbuns de lembranças.",
"Os índios e a ordem imperial.",
"Murilo Mendes, crítico de arte : a invenção do finito.",
"Poesia concreta brasileira : as vanguardas na encruzilhada modernista.",
"O discurso e a cidade.",
"Guimarães Rosa e a psicanálise : ensaios sobre imagem e escrita.",
"A urbanização brasileira.",
"Poesias reunidas.",
"Literatura e sociedade : estudos de teoria e história literária.",
"Presença da literatura brasileira : das origens ao Romantismo.",
"O descobrimento do Brasil.",
"Ensaios reunidos : 1946-1971.",
"Sertão do Rio Doce.",
"Em busca do tempo perdido.",
"A lágrima de um caet",
"A fonte subterrânea : José de Alencar e a retórica oitocentista.",
"Ficções de fundação : os romances nacionais da América Latina.",
"O relato de discurso na ficção narrativa : contributos para uma análise da construcção polifón",
"Forças armadas e política no Brasil.",
"Rosa em 2 tempos.",
"Os livros e os dias : um ano de leitura prazerosas.",
"Música do parnaso : edição fac-similar (1705-2005).",
"Um historiador fala de teoria e metodologia : ensaios.",
"A Europa diante do espelho.",
"Psicanálise da sociedade contemporânea.",
"Entre a casa e o armazém : relações sociais e experiência da urbanização, São Paulo, 1850-190",
"Princesa Isabel do Brasil : gênero e poder no século XIX.",
"Castro Alves.",
"A praça do diamante.",
"A prática do novo historicismo.",
"Pena de aluguel : escritores jornalistas no Brasil: 1904-2004.",
"Getúlio Vargas : o poder e o sorriso.",
"O livro no Brasil : sua história.",
"Hans Staden : primeiros registros escritos e ilustrados sobre o Brasil e seus habitantes.",
"Democracia e defesa nacional : a criação do Ministério da Defesa na presidência de FHC.",
"Patrimônio histórico e cultural.",
"A sátira e o engenho : Gregório de Matos e a Bahia do século XVII.",
"Poemas escolhidos.",
"Ministério do silêncio : a história do serviço secreto brasileiro de Washington Luís a Lula ( 1",
"Torquatália.",
"O consenso forjado : a grande imprensa e a formação da agenda ultraliberal no Brasil.",
"Discursos e relatórios na Convenção.",
"A identidade cultural na pós-modernidade.",
"Pelo sertão : histórias e paisagens.",
"Pela cidade.",
"O sindicalismo brasileiro após 1930.",
"Desenvolvimento e subdesenvolvimento.",
"Poesias completas de Raimundo Correia.",
"Rebeliões no Brasil colônia.",
"Não quero prosa.",
"A natureza na literatura brasileira : regionalismo pré-modernista.",
"Reis negros no Brasil escravista : história da festa de coroação de Rei Congo.",
"Diários.",
"Anais do IV Seminário Nacional Mulher e Literatura.",
"O Cântico dos Cânticos : um ensaio de interpretação através de suas traduções.",
"Arquitetura do século XX e outros escritos : Gregori Warchavchik.",
"Elementos de retórica literária.",
"Sem receita : ensaios e canções.",
"Razão da recusa : um estudo da poesia de Carlos Drummond de Andrade.",
"História. Ficçao. Literatura.",
"Os excluídos do reino : a Inquisição portuguesa e o degredo para o Brasil colônia.",
"A biblioteca à noite.",
"Brigada ligeira.",
"Teoria do drama burguês [século XVIII].",
"Aproximações : estudos de história e historiografia.",
"O patriotismo constitucional : Pernambuco, 1820-1822.",
"História econômica : estudos e pesquisas.",
"A política da nostalgia : um estudo das formas do passado.",
"Cultura popular do norte de Minas.",
"A ecologia de Marx : materialismo e natureza.",
"Choro : do quintal ao Municipal.",
"Portugal e Brasil na crise do antigo sistema colonial (1777-1808).",
"Nassau.",
"Infortúnios trágicos da constante Florinda.",
"A idéia e o figurado.",
"Brasil : paisagens de exceção: o litoral e o Pantanal Mato-Grossense: patrimônios básicos.",
"D. Pedro I : um herói sem nenhum caráter.",
"Triste fim de Policarpo Quaresma : romance.",
"O espaço moderno.",
"A idéia de história.",
"Nova reunião : 19 livros de poesia.",
"Lavoura arcaica.",
"Ignorância do sempre.",
"Santa Cecília.",
"Tudo que é sólido desmancha no ar : a aventura da modernidade.",
"O Brasil dos imigrantes.",
"Franklin Távora e o seu tempo.",
"Modernismos : ensaios sobre política, história e teoria da arte.",
"Estética : literatura e pintura, música e cinema.",
"O último leitor.",
"Lugar do mito : narrativa e processo social nas Primeiras estórias de Guimarães Rosa.",
"O método crítico de Sílvio Romero.",
"Os caminhos da riqueza dos paulistanos na primeira metade do oitocentos.",
"Cinzas do norte.",
"O Brasil nas letras de um pintor : Manuel de Araújo Porto Alegre (1806-1879).",
"Cartas a William Agel de Mello.",
"Cidadania no Brasil : o longo caminho.",
"O que é violência urbana.",
"Luz mediterrânea e outros poemas.",
"Mocambo : antropologia e história do processo de formação quilombola.",
"O negro no museu brasileiro : construindo identidades.",
"Tantas palavras.",
"Brás Cubas em três versões : estudos machadianos.",
"A utopia no cinema brasileiro : matrizes, nostalgia, distopias.",
"Há uma gota de sangue em cada Museu : a ótica museológica de Mário de Andrade.",
"Por um novo Machado de Assis : ensaios.",
"São Paulo em preto & branco : cinema e sociedade nos anos 50 e 60.",
"Ora (direis) puxar conversa! : ensaios literários.",
"Passos de Drummond.",
"Como eles agiam : os subterrâneos da ditadura militar : espionagem e polícia política.",
"A hora futurista que passou e outros escritos.",
"Sobrados e barões da velha São Paulo.",
"Vida política em tempo de crise : Rio de Janeiro (1808-1824).",
"Ler Saramago : o romance.",
"Autonomia e parceria : estados e transformação industrial.",
"Crônicas da província do Brasil.",
"Norma e conflito : aspectos da história de Minas no século XVIII.",
"Os Bruzundangas : sátira.",
"O paraíso destruído.",
"Presença portuguesa em São Paulo.",
"Civilização e revolta : os Botocudos e a catequese na província de Minas.",
"Tempo passado : cultura da memória e guinada subjetiva.",
"Joaquim Nabuco entre a política e a história.",
"Em defesa da sociedade : curso no Collège de France (1975-1976).",
"A construção do escravismo no Novo Mundo : do Barroco ao moderno, 1492-1800.",
"Florestan : a inteligência militante.",
"O Brasil não é longe daqui : o narrador, a viagem.",
"Orgulho de jamais aconselhar : a epistolografia de Mário de Andrade.",
"Índios do Nordeste : temas e problemas.",
"Imagens da Revolução Mexicana : o Museu Nacional de História do México (1940-1982).",
"Primeiras estórias.",
"A síncope das idéias : a questão da tradição na música popular brasileira.",
"Escravos e libertos no Brasil colonial.",
"Dialética do esclarecimento : fragmentos filosóficos.",
"A música popular no romance brasileiro.",
"Conceitos fundamentais da história da arte : o problema da evolução dos estilos na arte mais rece",
"Corpo de baile.",
"Ensaios premiados : a obra de Machado de Assis.",
"Sagarana.",
"Grande sertão: veredas : uma escritura biográfica.",
"O Brasil de Rosa : mito e história no universo rosiano : o amor e o poder.",
"Nas malhas da consciência : Igreja e Inquisição no Brasil : Nordeste 1640-1750.",
"Correio feminino.",
"Vira e mexe, nacionalismo : paradoxos do nacionalismo literário.",
"Ideais traídos.",
"Encruzilhadas da liberdade : histórias de escravos e libertos na Bahia, 1870-1910.",
"O sol e a sombra : política e administração na América Portuguesa do século XVIII.",
"Minas e currais : produção rural e mercado interno em Minas Gerais 1674-1807.",
"Teoria da poesia concreta : textos críticos e manifestos 1950-1960.",
"Chão de terra : e outros ensaios sobre São Paulo.",
"A formação do romance inglês : ensaios teóricos.",
"Bonde : saudoso paulistano.",
"O inimigo do rei : uma biografia de José de Alencar, ou, a mirabolante aventura de um romancista qu",
"Carnaval em branco e negro : carnaval popular paulistano, 1914-1988.",
"Hoje Cendrars parte para o Brasil.",
"Restauração arquitetônica : a experiência do SPHAN em São Paulo, 1937-1975.",
"A cultura do novo capitalismo.",
"Ver a terra : seis ensaios sobre a paisagem e a geografia.",
"O novo imperialismo.",
"Antônio Vieira e o Império universal : a Clavis prophetarum e os documentos inquisitoriais.",
"Rua do ouvidor 110 : uma história da Livraria José Olympio.",
"Glauber Rocha e a literatura de cordel : uma relação intertextual.",
"Recordações do escrivão Isaías Caminha : romance.",
"Introdução ao pensamento de Bakhtin.",
"Dona Flor da Cidade da Bahía : ensaios sobre a memória da vida cultural baiana.",
"Versificação portuguesa.",
"Formação da literatura brasileira : momentos decisivos 1750-1880.",
"Estudos de literatura brasileira e portuguesa.",
"O local da diferença : ensaios sobre memória, arte, literatura e tradução.",
"Recortes.",
"Patrimônio : atualizando o debate.",
"Literatura e sociedade.",
"A metáfora viva.",
"Formação econômica do Brasil.",
"Moderno e Brasileiro : a história de uma nova linguagem na arquitetura (1930-60).",
"A vila de São Paulo de Piratininga : fundação e representação.",
"Lundu do escritor díficil : canto nacional e fala brasileira na obra de Mário de Andrade.",
"Verbetes políticos da Enciclopédia.",
"Os tempos da fotografia : o efêmero e o perpétuo.",
"Gênero e artefato : o sistema doméstico na perspectiva da cultura material - São Paulo, 1870-1920",
"Machado de Assis : o enigma do olhar.",
"Cartas sertanejas  Procellarias.",
"Ensinar história no século XXI : em busca do tempo entendido.",
"Civilização material, economia e capitalismo : séculos XV-XVIII.",
"A literatura dos escritores : questões de crítica genética.",
"Não verás país nenhum : memorial descritivo.",
"América, Américas : arte e memória.",
"Escritos sobre historia.",
"Evaristo de Moraes, tribuno da república.",
"Folhetim : uma história.",
"A passagem do três ao um : crítica literária, sociologia, filologia.",
"Max Weber e a idéia de sociologia econômica.",
"Redes de criação : construção da obra de arte.",
"Minhas queridas.",
"Tietê, o rio que a cidade perdeu : São Paulo 1890-1940.",
"Proletários de casaca : trabalhadores do comércio carioca (1850-1911).",
"Da independência a Lula : dois séculos de política brasileira.",
"Extinção.",
"Do âmbito sagrado da Igreja ao cemitério público : transformações fúnebres em São Paulo (1850",
"O reino dos mestres : a tradição da jurema na umbanda nordestina.",
"Machado de Assis : um gênio brasileiro.",
"Introdução a Doutrina contra doutrina.",
"D. Pedro II.",
"Autoridade e conflito no Brasil colonial : o governo do Morgado de Mateus em São Paulo, 1765-1775.",
"Nossa senhora das flores.",
"Cultura popular : temas e questões.",
"Saudades de Rosa e sertão.",
"Crônicas e outros escritos de Tarsila do Amaral.",
"A Europa : gênese de uma civilização.",
"O império e as repúblicas do Pacífico : as relações do Brasil com Chile, Bolívia, Peru, Equado",
"A ilusão de desenvolvimento : nacionalismo e dominação burguesa nos anos JK.",
"Obras completas.",
"J. -B. Debret, historiador e pintor : a viagem pitoresca e histórica ao Brasil (1816-1839).",
"Por sobre os ombros : leituras do discurso cultural brasileiro.",
"A educação pela noite.",
"Eros, tecelão de mitos : a poesia de Safo de Lesbos.",
"Inscrever e apagar : cultura escrita e literatura (séculos XI-XVIII).",
"Macunaíma, o herói sem nenhum caráter.",
"Joaquim Manuel de Macedo, ou, Os dois Macedos : a luneta mágica do II Reinado.",
"Os filhos da Candinha.",
"Ironia e humor na literatura.",
"O sol do Brasil : Nicolas-Antoine Taunay e as desventuras dos artistas franceses na corte de d. Jo",
"Da guerrilha ao socialismo : a revolução cubana.",
"O primo Basílio na imprensa brasileira do século XIX : estética e história.",
"Em defesa da honra : moralidade, modernidade e nação no Rio de Janeiro (1918-1940).",
"A corte e o mundo : uma história do ano em que a família real portuguesa chegou ao Brasil.",
"O olho fotográfico : Marcel Gautherot e seu tempo.",
"Joaquim Nabuco.",
"Formação do pensamento político brasileiro : idéias e personagens.",
"Mínima mímica : ensaios sobre Guimarães Rosa.",
"Povos indígenas e a Lei dos Brancos : o direito à diferença.",
"Estação Brasil : conversas com músicos brasileiros.",
"Ser escravo no Brasil.",
"Retrato e sociedade na arte italiana : ensaios de história social da arte.",
"Caio Prado Jr : uma trajetória intelectual.",
"A aventura espiritual de Alvares de Azevedo : estudo e antologia.",
"Clarice Lispector com a ponta dos dedos.",
"Modernismo.",
"Mário de Andrade : a morte do poeta.",
"Hugonianas : poesias.",
"Joãozito : a infância de João Guimarães Rosa.",
"Formação da literatura brasileira : momentos decisivos 1750-1880.",
"Fragmentos setecentistas : escravidão, cultura e poder na América portuguesa.",
"Amigos escritos : quarenta e cinco anos de correspondência literária entre Monteiro Lobato e Godof",
"Cemitério : mais a peça teatral Destinos.",
"Ficção e confissão : ensaios sobre Graciliano Ramos.",
"Carnaval brasileiro : o vivido e o mito.",
"Jango e o golpe de 1964 na caricatura.",
"Literatura e marginalidade : um estudo sobre Malagueta, Perus e Bacanaço de João Antônio e Luuand",
"Memórias póstumas de Brás Cubas.",
"50 poemas escolhidos pelo autor.",
"Dom Casmurro.",
"Preconceito racial em Portugal e Brasil Colônia : os cristãos-novos e o mito da pureza de sangue.",
"Brancos e negros em São Paulo : ensaio sociológico sobre aspectos da formação, manifestações a",
"O abolicionismo.",
"O trem do corpo : estudo da poesia de Carlos Drummond de Andrade.",
"Ensaios de literatura ocidental : filologia e crítica.",
"A experiência do tempo : conceitos e narrativas na formação nacional brasileira (1813-1845).",
"As américas e a civilização : processo de formação histórica e causas do desenvolvimento desig",
"Guimarães Rosa : fronteiras, margens, passagens.",
"A jangada de pedra.",
"O Brasil entra em campo! : construções e reconstruções da identidade nacional (1930-1947).",
"Amar, verbo intransitivo : idílio.",
"Geografia política da água.",
"Uma colônia entre dois impérios : a abertura dos portos brasileiros 1800-1808.",
"Roteiro da viagem da cidade do Pará até as ultimas colônias do sertão da província (1768).",
"África e Brasil africano.",
"Canções da fôrca.",
"O Romantismo Paulista : os Ensaios Literários e o periodismo acadêmico de 1833 a 1860.",
"Os autos do processo de Vieira na Inquisição : 1660-1668.",
"Percurso do reconhecimento.",
"Manuel Bandeira e a música : com três poemas visitados.",
"Pensamento e lirismo puro na poesia de Cecília Meireles.",
"Por trás dos vidros.",
"Soldados da pátria : história do Exército Brasileiro, 1889-1937.",
"Um africano lê 'Macunaíma' : uma interpretação da rapsódia de Mário de Andrade com base em ele",
"O vento e o moinho : ensaios sobre arte moderna e contemporânea.",
"Visconde do Uruguai : centralização e federalismo no Brasil 1823-1866.",
"O vôo da Embraer : a competitividade brasileira na indústria de alta tecnologia.",
"Arqueologia das ciências e história dos sistemas de pensamento.",
"Castro Alves : imagens fragmentadas de um mito.",
"Antropologia cultural.",
"Notas sobre a formação social do Ceará (1680-1820).",
"Antropologia estrutural.",
"Tese e antítese.",
"A república consentida : cultura democrática e científica do final do império.",
"Teresina etc.",
"A aparição do demônio na fábrica : origens sociais do Eu dividido no subúrbio operário.",
"Poesia africana de língua portuguesa : antologia.",
"Cinematógrafo de letras : literatura, técnica e modernização no Brasil.",
"Marília de Dirceu.",
"A viagem marítima da família real : a transferência da corte portuguesa para o Brasil.",
"Órfãos do Eldorado.",
"Festas amazônicas : boi-bumbá, ciranda, sair",
"Quincas Borba.",
"Comunidades imaginadas : reflexões sobre a origem e a difusão do nacionalismo.",
"Uma história da cidade da Bahia.",
"Três vezes Machado de Assis.",
"O negro no mundo dos brancos.",
"Ser-tão natureza : a natureza em Guimarães Rosa.",
"Criatividade e dependência na civilização industrial.",
"Riso e melancolia : a forma shandiana em Sterne, Diderot, Xavier de Maistre, Almeida Garrett e Macha",
"O Brasil francês : as singularidades da França equinocial, 1612-1615.",
"Leréias : (historias contadas por eles mesmos).",
"Almanaque da TV Globo.",
"Jango : as múltiplas faces.",
"O ocidente dividido.",
"General Osorio.",
"Chutando a escada : a estratégia do desenvolvimento em perspectiva histórica.",
"D. João VI : um príncipe entre dois continentes.",
"A economia latino-americana : formação histórica e problemas contemporâneos.",
"Brasil, ficção geográfica : ciência e nacionalidade no país d'Os Sertões.",
"Espaço e método.",
"Obra imatura.",
"Armazém literário : ensaios.",
"História das lutas dos trabalhadores no Brasil.",
"Domingos Sodré, um sacerdote africano : escravidão, liberdade e candomblé na Bahia do século XIX",
"Uma história não contada : negro, racismo e branqueamento em São Paulo no pós-abolição.",
"As raízes e o labirinto da América Latina.",
"O Supremo Tribunal Federal e a construção da cidadania.",
"Profissão artista : pintoras e escultoras acadêmicas brasileiras.",
"A revolução urbana.",
"O suplício do Papai Noel.",
"Recado do nome : leitura de Guimarães Rosa à luz do nome de seus personagens.",
"A retórica de Rousseau e outros ensaios.",
"1968 : o ano que não terminou.",
"O bumba-boi maranhense em São Paulo.",
"Metamorfoses do espaço habitado : fundamentos teóricos e metodológicos da geografia.",
"A formação da classe operária inglesa.",
"A cidade, a noite e o cronista : São Paulo e Adoniran Barbosa.",
"Paraísos artificiais : contos.",
"Noções de paleografia e de diplomática.",
"Entre gueixas e samurais : fotografias e relatos de viagem.",
"O artista inconfessável.",
"O diário do padre Samuel Fritz.",
"História de Antônio Vieira.",
"Experiência neoconcreta : momento-limite da arte.",
"O direito de sonhar.",
"1968 : eles só queriam mudar o mundo.",
"Relato de um certo Oriente.",
"Uma festa brasileira celebrada em Rouen em 1550 : teogonia dos antigos povos do Brasil, um fragmento",
"O centro da cidade do Salvador : estudo de geografia urbana.",
"O idioma da mestiçagem : as irmandades de pardos na América portuguesa.",
"Os tambores da Chuva : o castelo.",
"Sete lições sobre as interpretações do Brasil.",
"Pequeno guia histórico das livrarias brasileiras.",
"Dificuldades da língua Portuguêsa : estudos e observaçoes.",
"Em um porão de São Paulo : o Lira Paulistana e a produção alternativa.",
"Rondon.",
"Obra completa em quatro volumes.",
"Traição : um jesuita a serviço do Brasil holandés processado pela Inquisição.",
"Paulistas e emboabas no coração das Minas : idéias, práticas e imaginário político no século",
"Caparaó : a primeira guerrilha contra a ditadura.",
"Apresentação da poesia brasileira : seguida de uma antologia.",
"Manual de geografia urbana.",
"A recolonização do Brasil pelas cortes : história de uma invenção historiográfica.",
"Caligramas.",
"Mário de Andrade.",
"JK : o artista do impossível.",
"Caetana diz não : histórias de mulheres da sociedade escravista brasileira.",
"O massacre : Eldorado do Carajás : uma história de impunidade.",
"O controle do imaginário & a afirmação do romance : Dom Quixote, As relações perigosas, Moll Fl",
"Poesia completa : [volume único].",
"A invenção do Nordeste e outras artes.",
"Veneno remédio : o futebol e o Brasil.",
"Adam Smith em Pequim : origens e fundamentos do século XXI.",
"Nelson Rodrigues : trágico, então moderno.",
"Duque de Caxias : o homem por trás do monumento.",
"1968 : o que fizemos de nós.",
"Macchado de Assis : fotógrafo do invisível: o escritor, sua vida e sua época em crônicas e image",
"Suplemento Literário : que falta ele faz! : 1956-1974 do artístico ao jornalístico : vida e morte",
"Do Brasil para as Américas : nos cartões-postais e álbuns de lembranças.",
"Livros e bibliotecas no Brasil colonial.",
"Modos de ser, modos de ver : viajantes europeus e escravos africanos no Rio de Janeiro (1808-1850).",
"Padres, celibato e conflito social : uma história da Igreja Católica no Brasil.",
"Os carnavais de rua e dos clubes na cidade de São Paulo : metamorfoses de uma festa (1923-1938).",
"Uma história da música popular brasileira : das origens à modernidade.",
"Formação da literatura brasileira : momentos decisivos, 1750-1880.",
"O poeta e a consciência crítica : uma linha de tradição, uma atitude de vanguarda.",
"Clarice : uma biografia.",
"Um nordeste em São Paulo : trabalhadores migrantes em São Miguel Paulista (1945-66).",
"Só.",
"A lógica das ciências sociais.",
"A arte de escrever : sobre a erudição e os eruditos  pensar por si mesmo  sobre a escrita e o es",
"Fausto : poema dramático.",
"Os sertões : (Campanha de Canudos).",
"Por uma economia política da cidade : o caso de São Paulo.",
"O guarani.",
"A música no cinema brasileiro : os inovadores anos sessenta.",
"Metalinguagem & outras metas : ensaios de teoria e crítica literária.",
"Os diários de Langsdorff.",
"Tenda dos milagres : romance.",
"Condessa de Barral : a paixão do imperador.",
"Poesia reunida.",
"Elos de melodia e letra : análise semiótica de seis canções.",
"Finalidades sem fim : ensaios sobre poesia e arte.",
"A formação do mercado de trabalho no Brasil.",
"Cururu.",
"A integração do negro na sociedade de classes.",
"Apesar de vocês : oposição à ditadura brasileira nos Estados Unidos, 1964-1985.",
"Da fachada atlântica à imensidão Amazônica : fronteira agrícola e integração territorial.",
"Ideologia e contraideologia : temas e variações.",
"Escravismo em São Paulo e Minas Gerais.",
"Mulheres negras do Brasil.",
"Modernismo : o fascínio da heresia de Baudelaire a Beckett e mais um pouco.",
"Lendas e romances.",
"A São Paulo de Menotti del Picchia : arquitetura, arte e cidade nas crônicas de um modernista.",
"Legislativo brasileiro em perspectiva comparada.",
"O rumor do tempo : e viagem à Armênia.",
"A teia mercantil : negócios e poderes em São Paulo Colonial, 1711-1765.",
"Livro de sonetos 1957 / 1967.",
"Natureza e cultura no Brasil (1870-1922).",
"Alusão e zombaria : citações e referências na ficção de Machado de Assis.",
"Dos canibais.",
"Diagnósticos do tempo : seis ensaios.",
"As musas sob assédio : literatura e indústria cultural no Brasil.",
"A literatura através do cinema : realismo magia e a arte da adaptação.",
"Gérard de Nerval : a escrita em trânsito.",
"Uma cantiga de se fechar os olhos... : mito e música em Guimarães Rosa.",
"Civilização material, economia e capitalismo séculos XV-XVIII.",
"Introdução à sociologia : (1968).",
"Estratégia, poder-saber.",
"Cultura com aspas : e outros ensaios.",
"João do Rio.",
"Hermenêutica e ideologias.",
"Vigiar e punir : nascimento da prisão.",
"Dialética negativa.",
"Invenção e memória.",
"Poesia completa e prosa : volume único.",
"Ponciá Vicêncio.",
"Teoria da vanguarda.",
"Câmara Cascudo e Mário de Andrade : cartas, 1924-1944.",
"A utopia antropofágica.",
"Pobreza urbana.",
"Escritos sobre teatro.",
"O guardador de segredos : ensaios.",
"História de uma viagem feita à terra do Brasil, também chamada América.",
"As origens do fascismo.",
"Machado e Borges : e outros ensaios sobre Machado de Assis.",
"Interdisciplinaridade, transdisciplinaridade no estudo e pesquisa da arte e cultura.",
"Línguas, poetas e bacharéis : uma crônica da tradução no Brasil.",
"A imaginação dialética : história da Escola de Frankfurt e do Instituto de Pesquisas Sociais, 19",
"Direitas em movimento : a campanha da mulher pela democracia e a ditadura no Brasil.",
"As estrelas descem à terra : a coluna de astrologia do Los Angeles Times : um estudo sobre supersti",
"Ensaios reunidos : escritos sobre Goethe.",
"A revolta da vacina : mentes insanas em corpos rebeldes.",
"A biblioteca esquecida de Hitler : os livros que moldaram a vida do Führer.",
"Escritos urbanos.",
"Espaços e caminhos de Guimarães Rosa : dimensões regionais e universalidade.",
"Escravismo no Brasil.",
"A classe média brasileira : ambições, valores e projetos de sociedade.",
"O loteamento do céu.",
"As meninas.",
"Resumo dos Cursos do Collège de France 1970-1982.",
"A condição urbana : a cidade na era da globalização.",
"O corpo da liberdade : reflexões sobre a pintura do século XIX.",
"Machado de Assis e a crítica internacional.",
"Colóquio Jorge Amado : 70 anos de Mar Morto.",
"A musica popular que surge na Era da Revolucao.",
"Cores de Rosa.",
"Semiótica à luz de Guimarães Rosa.",
"O altar & o trono : dinâmica do poder em O alienista.",
"Cultura imperial e projetos coloniais : séculos XV a XVIII.",
"A política da escravidão no império do Brasil, 1826-1865.",
"Educação e emancipação.",
"Drama em cena.",
"O problema da incredulidade no século XVI : a religião de Rabelais.",
"Raízes do Brasil.",
"Seleta.",
"Estilo tardio.",
"Notas de literatura I.",
"Intertexto : a escrita rapsódica: ensaio de leitura produtora.",
"Visconde de Cairu : itinerários de um ilustrado luso-brasileiro.",
"Obra seleta.",
"Nísia Floresta : vida e obra.",
"Condillac lúcido e translúcido.",
"Os tratados de delimitação do Brasil e a cartografia da época.",
"Mitos, emblemas, sinais : morfologia e história.",
"A vida social das coisas : as mercadorias sob uma perspectiva cultural.",
"Histórias sem data.",
"Contos completos.",
"Ritmo espontâneo : organicismo em Raizes do Brasil de Sérgio Buarque de Holanda.",
"Entre impérios : formação do Rio Grande na crise do sistema colonial português (1777-1822).",
"Sob o império das leis : Constituição e unidade nacional na formação do Brasil (1822-1834).",
"GasparGasparian : um fotógrafo.",
"Linha de fé : a Companhia de Jesus e a escravidão no processo de formação da sociedade colonial",
"Ao longo do rio : João Cabral e três poemas do Capibaribe.",
"Os parceiros do Rio Bonito : estudo sobre o caipira paulista e a transformação dos seus meios de v",
"A investigação etnológica no Brasil e outros ensaios.",
"A boiada.",
"A dama de espadas.",
"Américo : o homem que deu seu nome ao continente.",
"Revistas na era pós-verso : revistas experimentais e edições autônomas de poemas no Brasil, dos",
"O mal-estar na civilização, novas conferências introdutórias à psicanálise e outros textos : 1",
"A memória, a história, o esquecimento.",
"Os cangaceiros : ensaio de interpretação histórica.",
"História da sexualidade 1 : a vontade de saber.",
"L'équivoque épistolaire.",
"Registros fotográficos, patrimônio e memória da USP.",
"Ficções de Guimarães Rosa : perspectivas.",
"Sagarana : o Brasil de Guimarães Rosa.",
"Cláudio Manuel da Costa : [o letrado dividido].",
"A dialética da construção destrutiva na consagração do patrimônio mundial.",
"O direito dos escravos : lutas jurídicas e abolicionismo na provincia de São Paulo.",
"Hospedaria de imigrantes de São Paulo.",
"Trilogia do controle : O controle do imaginário Sociedade e discurso ficcional O fingidor e o cen",
"O alufá Rufino : tráfico, escravidão e liberdade no Atlântico Negro (c. 1822-c. 1853).",
"1922 : a semana que não terminou.",
"Ficção completa em dois volumes.",
"História da moda no Brasil : das influências às autorreferências.",
"Impressões do Brasil.",
"Entre a luxúria e o pudor : a história do sexo no Brasil.",
"Um discurso de André de Resende : pronunciado no Colégio das Artes Coimbra, 1551.",
"Registro : crônicas da Belle Époque carioca.",
"Crítica e crise : uma contribuição à patogênese do mundo burguês.",
"A mulher e a cidade : imagens da modernidade brasileira em quatro escritoras paulistas.",
"Geografias pós-modernas : a reafirmação do espaço na teoria social crítica.",
"Era uma vez em São Bernardo : o discurso sindical dos metalúrgicos, 1971-1982.",
"O trabalho do geógrafo no terceiro mundo.",
"Correspondência Mário de Andrade & Henriqueta Lisboa.",
"A era dos impérios, 1875-1914.",
"Livro : uma história viva.",
"Falando da sociedade : ensaios sobre as diferentes maneiras de representar o social.",
"Bestiário e discurso do gênero no descobrimento da América e na colonização do Brasil.",
"Ficção reunida.",
"Antônio Vieira : jesuíta do rei.",
"Memórias de um historiador de domingo.",
"O cavaleiro da esperança : vida de Luís Carlos Prestes.",
"Estrela breve : Lupe Cotrim: uma biografia literária.",
"Poesia traduzida.",
"A pérola das reduções jesuíticas : monografia de são Miguel.",
"Senzala insurgente : malungos, parentes e rebeldes nas fazendas de Campinas (1832).",
"Ô da rua! : o transeunte e o advento da modernidade em São Paulo.",
"Garranchos.",
"Grande sertão: veredas.",
"O romancista e o engenho : José Lins do Rego e o regionalismo nordestino dos anos 1920 e 1930.",
"A oficina do cosmógrafo ou a imagem do mundo no Renascimento.",
"A astronomia indigena.",
"Escassez de água e inundações na região metropolitana de São Paulo.",
"Graciliano Ramos e o desgosto de ser criatura.",
"Jesuítas e inquisição : cumplicidades e confrontações.",
"Cartas perto do coração : dois jovens escritores unidos pelo mistério da criação.",
"Essencial Padre Antonio Vieira.",
"Borges e a cabala : a busca do verbo.",
"Fábrica de contos : ciência e literatura em Machado de Assis.",
"Relações exteriores do Brasil, 1939-1950 : mudanças na natureza das relações Brasil-Estados Uni",
"Histórias da velha Totônia.",
"A imagem da linguagem na obra de Graciliano Ramos : uma análise da heterogeneidade discursiva nos r",
"A aventura do livro : do leitor ao navegador : conversações com Jean Lebrun.",
"Jornal de crítica, quarta série.",
"China tropical e outros escritos sobre a influência do Oriente na cultura luso-brasileira.",
"Brás, Bexiga e Barra Funda.",
"História e memória.",
"Melancolias, mercadorias : Dorival Caymmi, Chico Buarque, o pregão de rua e a canção popular-come",
"Escritos sobre arte e modernismo brasileiro.",
"A gênese da sociedade do espetáculo : teatro em Paris, Berlim, Londres e Viena.",
"Iniciação à literatura brasileira.",
"Caetés.",
"Almeida Júnior : gestos feitos de tinta.",
"Fio terra : 1996-2000.",
"Cabeza de Vaca.",
"A classe operária vai ao Parlamento : o Bloco Operário e Camponês do Brasil (1924-1930).",
"Economia política da urbanização.",
"Cartas a favor da escravidão.",
"Segundas estórias : uma leitura sobre Joãozito Guimarães Rosa.",
"Entre a literatura e a história.",
"Os antimodernos : de Joseph de Maistre a Roland Barthes.",
"A necessidade da arte : uma interpretação marxista.",
"Graciliano Ramos : a infância pelas mãos do escritor: um ensaio sobre a formação da subjetividad",
"Brasil, Argentina e Estados Unidos : conflito e integração na América do Sul : da Tríplice Alian",
"O cânone ocidental : os livros e a escola do tempo.",
"Seleção de contos brasileiros : a apresentação segue um critério geográfico, incluindo escrito",
"Confissões de Minas.",
"Poemas de Alberto Caeiro.",
"Homem ao termo : poesia reunida (1949-2005).",
"Cantares de perda e predileção.",
"Macário, ou do drama romântico em Álvares de Azevedo.",
"Um crime adormecido.",
"Amores & arte de amar.",
"Os epitáfios : poesia.",
"Mundo novo mesmo mundo : viajantes de língua alemã no Brasil.",
"Equador.",
"Vidas e doutrinas dos filósofos ilustres.",
"Pérola imperfeita : a história e as histórias na obra de Adriana Varejão.",
"Antes das Primeiras Estórias.",
"Violas e repentes : repentes populares, em prosa e verso : pesquisas folclóricas no nordeste brasil",
"Panorama do teatro brasileiro.",
"Viver.",
"Uma interpretação da literatura brasileira.",
"Ditadura e democracia no Brasil : do golpe de 1964 à constituição de 1988.",
"Música em 78 rotações : discos a todos os preços na São Paulo dos anos 30.",
"1964 : história do regime militar brasileiro.",
"Metrópole corporativa fragmentada : o caso de São Paulo.",
"Antologia poética : Murilo Mendes.",
"Correspondência.",
"Relatório.",
"Escravidão, pecuária e policultura : Alto Sertão da Bahia, século XIX.",
"Políticas culturais no Brasil : dos anos 1930 ao século XXI.",
"O bagaço da cana : os engenhos de açúcar do Brasil holandês.",
"Eça de Queiroz : uma biografia.",
"Cativos do reino : a circulação de escravos entre Portugal e Brasil, séculos 18 e 19.",
"O turista aprendiz.",
"Ao sol carta é farol : a correspondência de Mário de Andrade e outros missivistas.",
"No limiar do silêncio e da letra : traços da autoria em Clarice Lispector.",
"A arte do teatro : aulas de Anatol Rosenfeld (1968).",
"Estas estórias.",
"Não é errado falar assim! : em defesa do português brasileiro.",
"Entre o estúdio e a rua : a trajetória de Vincenzo Pastore, fotógrafo do cotidiano.",
"Índios no Brasil : história, direitos e cidadania.",
"O cinema-poesia de Joaquim Pedro de Andrade : passos da paixão mineira.",
"Escritores brasileiros do século XX : um testamento crítico.",
"Imprensa feminina e feminista no Brasil : século XIX: dicionário ilustrado.",
"Os cantos de Maldoror.",
"Sangue do céu.",
"Retrato do Brasil em cordel.",
"A lua e as fogueiras.",
"Os velhos marinheiros : duas histórias dos cais da Bahia.",
"Manual da redação : as normas de escrita e conduta do principal jornal do país.",
"A tragédia de Hamlet, príncipe da Dinamarca.",
"História econômica e social do estado de São Paulo.",
"História do carnaval carioca.",
"O futebol brasileiro, bicampeão do mundo.",
"História concisa do teatro brasileiro : 1570-1908.",
"Invenção de Orfeu.",
"Gregório de Matos.",
"O mesmo mar.",
"Arquivos para quê? : textos escolhidos.",
"Linha na roca, linha na pauta : o tecer da memória na obra O tempo e o vento, de Erico Verissimo.",
"As universidades e o regime militar : cultura política brasileira e modernização autoritária.",
"A cartografia impressa do Brasil, 1506-1922 : os 100 mapas mais influentes.",
"Memória, História e historiografia.",
"A cidade no Brasil.",
"Os leitores de Machado de Assis : o romance machadiano e o público de literatura no século 19.",
"Esplendor do barroco luso-brasileiro.",
"Grande sertão : veredas.",
"Benjamin Abrahão : entre anjos e cangaceiros.",
"Mário de Andrade e Carl Gustav Jung em Macunaíma, o herói sem nenhum caráter.",
"Mário de Andrade : poesia, amor e música.",
"Capas de Santa Rosa.",
"Teatro reunido.",
"A esquerda e o golpe de 64.",
"Pra frente, Brasil! : do Maracanazo aos mitos de Pelé e Garrincha, a dialética da ordem e da desor"]

def getISBN(titulo):
  #retorna todos os itens do grafo
  itens = graph.run('''MATCH (n:Item {titulo:"'''+titulo+'''"}) RETURN n.isbn, n.titulo''').data()
  return itens[0]['n.isbn'], itens[0]['n.titulo']

def getISBNpuro(titulo):
    try:
        itens = graph.run('''CALL db.index.fulltext.queryNodes("itens", "''' + titulo + '''") 
        YIELD node, score RETURN node.titulo''').data()
        isbn = getISBN(itens[0]['node.titulo'])
        if itens == []:
            isbn = 'Não existe'
    except:
        isbn = 'Erro'
    return isbn

inicio = time.time()
count = 0
for name in names:
    isbn = getISBNpuro(name)
    if isbn == 'Erro' or isbn == 'Não existe':
        count += 1
    else:
        print(name, ": ", isbn)
fim = time.time()
print("Tempo: ",fim - inicio)
print("Não encontrou:",count)
